# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://211.232.166.228:6012/nmb/acct/get/member
Content-Type: application/json

{
  "id" : "test@test.net",
  "password" : "dekerTest",
  "platformCode" : "P01"
}

> {%
client.global.set("jwtToken", response.body.data.jwtToken);
client.log(client.global.get("jwtToken"));
%}

###

POST http://211.232.166.228:6012/mb/post/get/my-post-list
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
  "currentPageNo" : 3
}

> {%
client.log(client.global.get("jwtToken"));
%}
###